name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:

jobs:
  build_release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        pip install psutil==5.9.5
        pip install requests==2.31.0
        pip install pyinstaller==6.4.0

    - name: Build release executable
      run: pyinstaller --onefile --noconsole --icon=icon.ico --add-data="icon.ico;." --add-data="sv_ttk;sv_ttk" robloxstudiomanager.py

    - name: Store Release Artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v2
      with:
        name: RobloxStudioManagerRelease
        path: ./dist/robloxstudiomanager.exe

    - name: Create Release and Upload Asset
      if: github.event_name == 'push'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v1.${{ github.run_number }}"
        release_name: Release v1.${{ github.run_number }}
        body: |
          An automated release.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.event_name == 'push'
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/robloxstudiomanager.exe
        asset_name: RobloxStudioManager.exe
        asset_content_type: application/octet-stream

  build_debug:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        pip install psutil==5.9.5
        pip install requests==2.31.0
        pip install pyinstaller==6.4.0

    - name: Build debug executable
      run: pyinstaller --onefile --icon=icon.ico --add-data="icon.ico;." --add-data="sv_ttk;sv_ttk" robloxstudiomanager.py

    - name: Store Debug Artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v2
      with:
        name: RobloxStudioManagerDebug
        path: ./dist/robloxstudiomanager.exe

