name: Build RobloxStudioManager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Modify FluentWidgets
        run: |
          $QFLUENT_PATH = python -c "import sys; sys.stdout = open('nul', 'w'); import qfluentwidgets; sys.stdout = sys.__stdout__;  print(qfluentwidgets.__path__[0])"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Firebladedoge229/PyQt-Fluent-Widgets/refs/heads/master/qfluentwidgets/common/config.py" -OutFile "$QFLUENT_PATH/common/config.py"

      - name: Install Nuitka
        run: |
          pip install nuitka

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install UPX using Chocolatey
        run: choco install upx

      - name: Build RobloxStudioManager
        run: |
          nuitka src/main.py --standalone --onefile --windows-disable-console --output-filename=RobloxStudioManager --windows-icon-from-ico=images/logo.ico --enable-plugin=pyqt5 --include-data-files="src/ui_components.py=ui_components.py" --include-data-files="src/downloader.py=downloader.py" --include-data-files="src/logic.py=logic.py" --include-data-files="data/fastflags.json=fastflags.json" --include-data-files="data/options.json=options.json" --include-data-files="images/logo.png=logo.png" --include-data-files="images/RobloxStudioManager.png=RobloxStudioManager.png"
        working-directory: ./

      - name: Build RobloxStudioManagerDebug
        run: |
          nuitka src/main.py --standalone --onefile --output-filename=RobloxStudioManagerDebug --windows-icon-from-ico=images/logo.ico --enable-plugin=pyqt5 --include-data-files="src/ui_components.py=ui_components.py" --include-data-files="src/downloader.py=downloader.py" --include-data-files="src/logic.py=logic.py" --include-data-files="data/fastflags.json=fastflags.json" --include-data-files="data/options.json=options.json" --include-data-files="images/logo.png=logo.png" --include-data-files="images/RobloxStudioManager.png=RobloxStudioManager.png"
        working-directory: ./

      - name: Compress Executable with UPX
        run: |
          upx --best --lzma dist/RobloxStudioManager.exe
          upx --best --lzma dist/RobloxStudioManagerDebug.exe

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobloxStudioManager
          path: "RobloxStudioManager.exe"

      - name: Upload Development Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobloxStudioManagerDebug
          path: "RobloxStudioManagerDebug.exe"
