name: Build RobloxStudioManager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Modify FluentWidgets
        run: |
          QFLUENT_PATH=$(python -c "import qfluentwidgets; print(qfluentwidgets.__path__[0])")
          curl -o "$QFLUENT_PATH/common/config.py" https://raw.githubusercontent.com/Firebladedoge229/PyQt-Fluent-Widgets/refs/heads/master/qfluentwidgets/common/config.py

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build RobloxStudioManager
        run: |
          pyinstaller --onefile --noconsole --name=RobloxStudioManager --icon=images/logo.ico --add-data="src/ui_components.py:." --add-data="src/downloader.py:." --add-data="src/logic.py:." --add-data="data:." --add-data="images/logo.png:." --add-data="images/RobloxStudioManager.png:." src/main.py
        working-directory: ./

      - name: Build RobloxStudioManagerDebug
        run: |
          pyinstaller --onefile --name=RobloxStudioManagerDebug --icon=images/logo.ico --add-data="src/ui_components.py:." --add-data="src/downloader.py:." --add-data="src/logic.py:." --add-data="data:." --add-data="images/logo.png:." --add-data="images/RobloxStudioManager.png:." src/main.py
        working-directory: ./

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobloxStudioManager
          path: "dist/RobloxStudioManager.exe"

      - name: Upload Development Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobloxStudioManagerDebug
          path: "dist/RobloxStudioManagerDebug.exe"
